// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3wz1A7nP2SCfIYydE31pYrVmjxqHcy_M',
    appId: '1:750817095550:web:70e5c0e4911770fd6e0d2f',
    messagingSenderId: '750817095550',
    projectId: 'hf-bd23',
    authDomain: 'hf-bd23.firebaseapp.com',
    storageBucket: 'hf-bd23.firebasestorage.app',
    measurementId: 'G-398CE10PHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkeY42GO66yubqt-3R5tqQzwmI1AaZNM',
    appId: '1:750817095550:android:ebfa90a80acd28c96e0d2f',
    messagingSenderId: '750817095550',
    projectId: 'hf-bd23',
    storageBucket: 'hf-bd23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD87yn-IelO23rFiUJUi4Lrb7PPsAl5UPA',
    appId: '1:750817095550:ios:13eb66b3af52a6456e0d2f',
    messagingSenderId: '750817095550',
    projectId: 'hf-bd23',
    storageBucket: 'hf-bd23.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD87yn-IelO23rFiUJUi4Lrb7PPsAl5UPA',
    appId: '1:750817095550:ios:13eb66b3af52a6456e0d2f',
    messagingSenderId: '750817095550',
    projectId: 'hf-bd23',
    storageBucket: 'hf-bd23.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3wz1A7nP2SCfIYydE31pYrVmjxqHcy_M',
    appId: '1:750817095550:web:8fd0ec63016871886e0d2f',
    messagingSenderId: '750817095550',
    projectId: 'hf-bd23',
    authDomain: 'hf-bd23.firebaseapp.com',
    storageBucket: 'hf-bd23.firebasestorage.app',
    measurementId: 'G-09530SH2EL',
  );
}
